### ISSUE TITLE
明明有仓位，通达信发出卖出预警，tdxtrader却无法识别到仓位导致无法卖出

### ISSUE THREAD

**Issue by victorhuyue** [zsrl/tdxtrader#12]
![有仓位](https://github.com/user-attachments/assets/24104025-53e7-4939-b284-19e4a2e0329e)
![有仓位但无法卖出1](https://github.com/user-attachments/assets/a2ede784-122e-4460-9e1f-426a8b8a80a5)

**Comment by zsrl** [comment]
已复现并修复，xtquant的`xt_trader.query_stock_position`方法查不到etf持仓，换成`xt_trader.query_stock_positions`可以了，更新0.3.8
